/* --------------------------------------- */
/*      Variables and imports section      */
/* --------------------------------------- */
// sauce model import
const Sauce = require("../models/Sauce");

// fs module import
const fs = require("fs");

/* -------------------------------- */
/*      Get controlers section      */
/* -------------------------------- */
// exporting the controler to get all the sauces
exports.getAllSauces = (request, response, next) => {
  // finding all the sauces
  Sauce.find()
    // if it is OK set the answer to 200 and send sauces
    .then((sauces) => response.status(200).json(sauces))
    // if not send the error
    .catch((error) => response.status(400).json({ error }));
};

// exporting the controler to get one sauce
exports.getOneSauce = (request, response, next) => {
  // find the sauce which id is in the parameters of the request
  Sauce.findOne({ _id: request.params.id })
    // if it is OK set the answer to 200 and send the sauce
    .then((sauce) => {
      response.status(200).json(sauce);
    })
    // if not send the error
    .catch((error) => response.status(400).json({ error }));
};

/* --------------------------------- */
/*      Post controlers section      */
/* --------------------------------- */
// exporting route to create sauces
exports.createSauce = (request, response, next) => {
  // recover the sauce object (as a string) from the request
  const sauceObject = JSON.parse(request.body.sauce);
  // the autogenerated id is deleted to use MongoDB id
  delete sauceObject._id;
  // a new sauce is built from the sauceObject
  const sauce = new Sauce({
    // spread sauceObject properties to sauce
    ...sauceObject,
    // seting the right url for the image
    imageUrl: `${request.protocol}://${request.get("host")}/images/${
      request.file.filename
    }`,
    likes: 0,
    dislikes: 0,
    usersLiked: [],
    usersDisliked: [],
  });
  // sauce is saved in MongoDB
  sauce
    .save()
    .then(() =>
      response.status(201).json({ message: "Sauce saved in database !" })
    )
    .catch((error) => response.status(400).json({ error }));
};

/* -------------------------------- */
/*      Put controlers section      */
/* -------------------------------- */
// exporting route to modify an existing sauce
exports.modifySauce = (request, response, next) => {
  console.log("présence d'un fichier :", request.file);
  // sauce object is either :
  const sauceObject = request.file
    ? {
        // pared from stringified sauce if there is a file, spreaded
        ...JSON.parse(request.body.sauce),
        // the url of the new image saved
        imageUrl: `${request.protocol}://${request.get("host")}/images/${
          request.file.filename
        }`,
      }
    : {
        // the body of the request, spreaded
        ...request.body,
      };
  console.log("objet sauce présent dans la requête", sauceObject);

  // code to be sure that the sauce belong to the user trying to modify it
  // if (sauceObject.userId){}
};
